#############################################################################
# Makefile for building: oilwater.app/Contents/MacOS/oilwater
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  oilwater.pro
# Template: app
# Command: /Users/alex/Qt5.6.0/5.6/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile oilwater.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Cellar/glew/1.13.0/include -I/usr/local/Cellar/glfw3/3.1.2/include -I../../../../Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers -I../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../../Qt5.6.0/5.6/clang_64/mkspecs/macx-clang -F/Users/alex/Qt5.6.0/5.6/clang_64/lib
QMAKE         = /Users/alex/Qt5.6.0/5.6/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = oilwater1.0.0
DISTDIR = /Users/alex/Desktop/dev/oilwater/oilwater/.tmp/oilwater1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/alex/Qt5.6.0/5.6/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/alex/Qt5.6.0/5.6/clang_64/lib -L/usr/local/Cellar/glew/1.13.0/lib -L/usr/local/Cellar/glfw3/3.1.2/lib -framework OpenGL -lglfw3 -lGLEW -framework IOKit -framework CoreFoundation -framework CoreVideo -framework Cocoa -v -framework QtGui -framework QtCore -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/camera.cpp \
		src/geometry.cpp \
		src/initbuff.cpp \
		src/kernel.cpp \
		src/main.cpp \
		src/model.cpp \
		src/position.cpp \
		src/terminal.cpp \
		src/network.cpp 
OBJECTS       = camera.o \
		geometry.o \
		initbuff.o \
		kernel.o \
		main.o \
		model.o \
		position.o \
		terminal.o \
		network.o
DIST          = res/map_test/shaders/vert.glsl \
		res/map_test/shaders/frag.glsl \
		res/load_sprite_inside/shaders/vert.glsl \
		res/load_sprite_inside/shaders/frag.glsl \
		res/load_sprite_outside/shaders/vert.glsl \
		res/load_sprite_outside/shaders/frag.glsl \
		res/box_red/shaders/vert.glsl \
		res/box_red/shaders/frag.glsl \
		res/boom_test_sprite/shaders/vert.glsl \
		res/boom_test_sprite/shaders/frag.glsl \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/resources.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/moc.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/lex.prf \
		oilwater.pro src/camera.h \
		src/geometry.h \
		src/glmath.hpp \
		src/initbuff.hpp \
		src/kernel.h \
		src/model.h \
		src/position.h \
		src/terminal.h \
		src/network.h src/camera.cpp \
		src/geometry.cpp \
		src/initbuff.cpp \
		src/kernel.cpp \
		src/main.cpp \
		src/model.cpp \
		src/position.cpp \
		src/terminal.cpp \
		src/network.cpp
QMAKE_TARGET  = oilwater
DESTDIR       = 
TARGET        = oilwater.app/Contents/MacOS/oilwater


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d oilwater.app/Contents/MacOS/ || mkdir -p oilwater.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: oilwater.pro ../../../../Qt5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/resources.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/moc.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/lex.prf \
		oilwater.pro \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile oilwater.pro
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/qdevice.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/device_config.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/unix.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/mac.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/macx.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/clang.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/qconfig.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/default_post.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/resources.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/moc.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/yacc.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/lex.prf:
oilwater.pro:
../../../../Qt5.6.0/5.6/clang_64/lib/QtGui.framework/QtGui.prl:
../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile oilwater.pro

qmake_all: FORCE

oilwater.app/Contents/PkgInfo: 
	@test -d oilwater.app/Contents || mkdir -p oilwater.app/Contents
	@$(DEL_FILE) oilwater.app/Contents/PkgInfo
	@echo "APPL????" > oilwater.app/Contents/PkgInfo
oilwater.app/Contents/Resources/empty.lproj: 
	@test -d oilwater.app/Contents/Resources || mkdir -p oilwater.app/Contents/Resources
	@touch oilwater.app/Contents/Resources/empty.lproj
	
oilwater.app/Contents/Info.plist: 
	@test -d oilwater.app/Contents || mkdir -p oilwater.app/Contents
	@$(DEL_FILE) oilwater.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.oilwater,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,oilwater,g" -e "s,@LIBRARY@,oilwater,g" -e "s,@TYPEINFO@,????,g" ../../../../Qt5.6.0/5.6/clang_64/mkspecs/macx-clang/Info.plist.app >oilwater.app/Contents/Info.plist

all: Makefile \
		oilwater.app/Contents/PkgInfo \
		oilwater.app/Contents/Resources/empty.lproj \
		oilwater.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/camera.h src/geometry.h src/glmath.hpp src/initbuff.hpp src/kernel.h src/model.h src/position.h src/terminal.h src/network.h $(DISTDIR)/
	$(COPY_FILE) --parents src/camera.cpp src/geometry.cpp src/initbuff.cpp src/kernel.cpp src/main.cpp src/model.cpp src/position.cpp src/terminal.cpp src/network.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r oilwater.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

camera.o: src/camera.cpp src/camera.h \
		src/glmath.hpp \
		src/position.h \
		/usr/local/Cellar/glfw3/3.1.2/include/GLFW/glfw3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o src/camera.cpp

geometry.o: src/geometry.cpp src/geometry.h \
		src/glmath.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geometry.o src/geometry.cpp

initbuff.o: src/initbuff.cpp src/initbuff.hpp \
		src/model.h \
		/usr/local/Cellar/glew/1.13.0/include/GL/glew.h \
		src/glmath.hpp \
		src/position.h \
		src/camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o initbuff.o src/initbuff.cpp

kernel.o: src/kernel.cpp src/model.h \
		/usr/local/Cellar/glew/1.13.0/include/GL/glew.h \
		src/glmath.hpp \
		src/position.h \
		src/camera.h \
		src/kernel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kernel.o src/kernel.cpp

main.o: src/main.cpp ../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		/usr/local/Cellar/glew/1.13.0/include/GL/glew.h \
		/usr/local/Cellar/glfw3/3.1.2/include/GLFW/glfw3.h \
		src/model.h \
		src/glmath.hpp \
		src/position.h \
		src/camera.h \
		src/initbuff.hpp \
		src/kernel.h \
		src/terminal.h \
		src/network.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

model.o: src/model.cpp src/model.h \
		/usr/local/Cellar/glew/1.13.0/include/GL/glew.h \
		src/glmath.hpp \
		src/position.h \
		src/camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o src/model.cpp

position.o: src/position.cpp src/position.h \
		src/glmath.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o position.o src/position.cpp

terminal.o: src/terminal.cpp /usr/local/Cellar/glfw3/3.1.2/include/GLFW/glfw3.h \
		src/terminal.h \
		src/kernel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o terminal.o src/terminal.cpp

network.o: src/network.cpp ../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		src/network.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		src/camera.h \
		src/glmath.hpp \
		src/position.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o network.o src/network.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

